name: Publish package
on:
  push:
    tags:
      - "*"
jobs:
  Build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - run: pip install --upgrade wheel
      - uses: actions/checkout@v3
      - run: python setup.py sdist bdist_wheel
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          